server:
  port: 9201
#添加rabbitmq配置
spring:
  rabbitmq:
    host: 192.168.199.231
    port: 5672
    username: guest
    password: guest
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:9000/eureka
#  instance:
#    prefer-ip-address: true
