server:
  port: 9201

spring:
  application:
    name: config-client
  cloud:
    config:
      label: master
      uri: http://localhost:9200/
      profile: dev
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:9000/eureka
#  instance:
#    prefer-ip-address: true
