server:
  port: 9101

spring:
  application:
    name: service-feign
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka
  instance:
    prefer-ip-address: true
#打开feign的断路器设置
feign.hystrix.enabled: true