server:
  port: 9200

spring:
  cloud:
    config:
      server:
        git:
          #git地址
          uri: https://gitee.com/angelo_zou/springCloud
          #git用户名
          username:
          #密码
          password:
          search-paths: config
      #分支
      label: master
  application:
    name: config-server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka
  instance:
    prefer-ip-address: true